version: '3'
services:
  scala-dev:
    container_name: scala
    build: .
    ports:
      - "8900:5900"  # VNC port (host:container)
      - "8080:8080"  # noVNC web port
    volumes:
      - ./:/app
    environment:
      - DISPLAY=:0
    stdin_open: true
    tty: true
    command: /bin/bash